### PR TITLE
(bug): dirty git work tree, (chore): update to new jenkins image

### LINKED ISSUE #48: (bug) SSH-Key generation: git work-tree is left "dirty" when executing the key generation script
Ref PR #42 

When the key generation script is executed, the compose file and keys are seen as git changes (dirty git worktree)

### PR DESCRIPTION
**Pull request by ash-sxn**
- resolves #48 
- update jenkins/jenkins:  20.401.1-lts => 20.401.2-lts
- the completes Milestone 0
- this uses `git restore docker-compose.yaml` in jenkins_teardown.sh to deal with docker-compose.yaml's git issue  
- #55  was also fixed from `jenkins_teardown.sh`, I forgot to add it in the PR, should I add it to this one? 
- pinging mentors @berviantoleo @gounthar @jmMeessen

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -0,0 +1,6 @@
+# Ignore secrets folder
+secrets/*
+experimental_docker_compose_files/02_custom_docker_file_connecting_agent_and_controller/secrets/*
+# Ignore dockerfiles because get's changed during the gitpodURL.sh
+dockerfiles/jenkins.yaml
```
Comment (gounthar) [inline .gitignore:5]: If you ignore `dockerfiles`, the changes you'll make in them won't be part of the repo.

File: jenkins_init.sh [hunk 2]
```diff
@@ -32,12 +32,12 @@ check_wsl() {
     if [[ $(grep -i Microsoft /proc/version) ]]; then
         echo "Running on WSL"
         if ! command -v dos2unix &> /dev/null; then
-            if sudo -n true 2>/dev/null; then
-                echo "dos2unix not found, installing..."
-                sudo apt-get update && sudo apt-get install -y dos2unix
-            else
+            if [[ $(id -u) -ne 0 ]]; then
```
Comment (gounthar) [inline jenkins_init.sh:35]: It's a nice touch to install `dos2unix`, but it won't work for each and every distro.
Let's keep it like that for the time being.
The need for `dos2unix` can't be linked to a bad `git` configuration (it used to be my case) or to the use of a directory under `C:` (seen as `/mnt/c` instead of something that is on `/home` for example).

I have to reconfigure my PC thanks to something [like that](https://www.jetbrains.com/help/idea/how-to-use-wsl-development-environment-in-product.html#create_project_for_wsl).

**Review by gounthar — CHANGES_REQUESTED** [review]

**Review by gounthar — APPROVED** [review]

**Comment by gounthar** [comment]
It's better when you make atomic changes, and address only one issue per PR.
But... In this case, it's not major and we're running out of time, so I'll merge it.
Thanks.
